version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "8887:8887"
    volumes:
      - ./service/chat/api/etc/chat-api.yaml:/etc/chat-api.yaml
      - ./tmp:/tmp/image
    privileged: true
    restart: always
